[keyboard]
name = "RMK Keyboard"
product_name = "My RMK Keyboard"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "haobo"
chip = "nrf52840"

[matrix]
# 输入和输出引脚是必需的ipunt→rows，output→cols
input_pins = ["P0_09", "P0_24", "P0_00", "P0_13"]
output_pins = ["P1_11", "P0_30", "P1_10", "P0_10"]
# 警告：目前 row2col/col2row 在 RMK 的特性门中设置，只有在使用云编译时，此处的 row2col 配置才有效
# row2col = true

[layout]
rows = 4
cols = 4
layers = 2
keymap = [
    [
        ["A", "A", "A", "A"],
        ["Kc1", "Kc2", "Kc3", "A"],
        ["LCtrl", "MO(1)", "LShift", "A"],
        ["OSL(1)", "LT(2, Kc9)", "LM(1, LShift | LGui)", "A"]
    ],
    [
        ["TO(1)", "TT(1)", "TG(2)", "A"],
        ["DF(1)", "_", "_", "A"],
        ["_", "_", "_", "A"],
        ["_", "_", "_", "A"]
    ],
]

[[encoder]]
pin_a = "P1_13"
pin_b = "P0_02"

# Phase 是旋转编码器的工作模式。
# 可用模式：
# - default：兼容 EC11，分辨率 = 1
# - e8h7：分辨率 = 2，反向 = true
# - resolution：自定义分辨率，分辨率值和反向应稍后指定
phase = "default" 

# 分辨率表示编码器每转过一个棘爪产生的脉冲数。
# 例如，如果您的旋转编码器总共有 30 个棘爪，并且每旋转 360 度产生 15 个脉冲，则分辨率 = 30/15 = 2。
# 棘爪数和脉冲数可以在您的编码器数据手册中找到
# resolution = 2

# 旋转编码器的方向是否反向。
# reverse = false

[[encoder]]
pin_a = "P1_09"
pin_b = "P0_05"
phase = "resolution"
resolution = 2

[[encoder]]
pin_a = "P1_10"
pin_b = "P0_03"
phase = "resolution"
resolution = 2
 
[light]
# 默认情况下，所有灯光引脚都是高电平有效，如果希望低电平有效，请取消注释
# capslock.pin = "P0_30"
# capslock.low_active = false
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# 如果没有使用灯光引脚，请忽略
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# 存储功能默认启用
# enabled = false
# clear_storage = true

[ble]
enabled = true
# vddh 具有内部电压分压器
battery_adc_pin = "vddh"
# Or
# battery_adc_pin = "P0_04"
# adc_divider_measured = 2000
# adc_divider_total = 2806
# charge_state.pin = "P0_25"
# charge_state.low_active = false
# charge_led.pin = "P0_29"
# charge_led.low_active = false

[behavior.combo]
timeout = "150ms"
combos = [
  # 同时按下 J 和 K 键以输出 "L"
  { actions = ["J", "K"], output = "L" },
  # 同时按下 F 和 D 键切换到层 2，但仅在层 0 上有效
  { actions = ["F", "D"], output = "TO(1)", layer = 0 },
  # 三键组合，按下 A、S 和 D 键以输出 "X"
  { actions = ["A", "S", "D"], output = "X" }
]

[behavior.fork]
forks = [
    # Shift + '.' 输出 ':' 键
  { trigger = "Dot", negative_output = "Dot", positive_output = "WM(Semicolon, LShift)", match_any = "LShift|RShift" },

  # Shift + ',' 输出 ';' 键，但前提是没有按下 Alt 键
  { trigger = "Comma", negative_output = "Comma", positive_output = "Semicolon", match_any = "LShift|RShift", match_none = "LAlt|RAlt" },  
  
  # 默认情况下，左括号输出 '{'，按下 Shift 键时输出 '['  
  { trigger = "LeftBracket", negative_output = "WM(LeftBracket, LShift)", positive_output = "LeftBracket", match_any = "LShift|RShift" },

  # 翻转 Shift 对 'x'/'X' 的影响
  { trigger = "X", negative_output = "WM(X, LShift)", positive_output = "X", match_any = "LShift|RShift" },

  # F24 通常输出 'a'，除非按下左 Shift 或 Ctrl 键，在这种情况下会触发一个宏 
  { trigger = "F24", negative_output = "A", positive_output = "Macro1", match_any = "LShift|LCtrl" },

  # 如果按下鼠标按键 1（在键盘上），则交换 Z 和 Y 键（请注意，这些键不能绑定，以避免无限的 fork 循环！) 
  { trigger = "Y", negative_output = "Y", positive_output = "Z", match_any = "MouseBtn1", bindable = false },
  { trigger = "Z", negative_output = "Z", positive_output = "Y", match_any = "MouseBtn1", bindable = false },

  # Shift + Backspace 输出 Delete 键（在层点击/按住内）
  { trigger = "LT(2,Backspace)", negative_output = "LT(2,Backspace)", positive_output = "LT(2,Delete)", match_any = "LShift|RShift" },

  # Ctrl + 播放/暂停 将发送下一曲。MediaPlayPause -> MediaNextTrack
  # Ctrl + Shift + 播放/暂停 将发送上一曲。MediaPlayPause -> MediaPrevTrack
  # Alt + 播放/暂停 将发送音量增大。MediaPlayPause -> AudioVolUp
  # Alt + Shift + 播放/暂停 将发送音量减小。MediaPlayPause -> AudioVolDown
  # Ctrl + Alt + 播放/暂停 将发送亮度增大。MediaPlayPause -> BrightnessUp
  # Ctrl + Alt + Shift + 播放/暂停 将发送亮度减小。MediaPlayPause -> BrightnessDown
  # ( 注意，fork 链的触发键和立即触发键可以是“虚拟键”， 
  #   它永远不会输出，例如 F23，但这里演示了多个覆盖。)
  { trigger = "MediaPlayPause", negative_output = "MediaPlayPause", positive_output = "MediaNextTrack", match_any = "LCtrl|RCtrl", bindable = true },
  { trigger = "MediaNextTrack", negative_output = "MediaNextTrack", positive_output = "BrightnessUp", match_any = "LAlt|RAlt", bindable = true },
  { trigger = "BrightnessUp", negative_output = "BrightnessUp", positive_output = "BrightnessDown", match_any = "LShift|RShift", bindable = false },
  { trigger = "MediaNextTrack", negative_output = "MediaNextTrack", positive_output = "MediaPrevTrack", match_any = "LShift|RShift", match_none = "LAlt|RAlt", bindable = false},
  { trigger = "MediaPlayPause", negative_output = "MediaPlayPause", positive_output = "AudioVolUp", match_any = "LAlt|RAlt", match_none = "LCtrl|RCtrl", bindable = true },
  { trigger = "AudioVolUp", negative_output = "AudioVolUp", positive_output = "AudioVolDown", match_any = "LShift|RShift", match_none = "LCtrl|RCtrl", bindable = false } 
]